"""Pocket labelling for the sparse (virtual-node) complex.

The sparse complex keeps a voxel iff ``min(g0, g1) < tau_mask`` and replaces every
connected region of masked voxels -- a *pocket* -- by one virtual node. This module
computes those pockets, and nothing else: it is matcher- and loss-independent, and the
C++ matcher validates the labels it receives.

``fine`` -- 26-connected components of the **masked voxels** (8-connected in 2D).
    Consumers: the top-dimension dual union-find and the dim-1 cone apexes.

    Why 26 and not something else: in the V-construction voxels *are* vertices, so
    the kept foreground is 6-connected and the masked complement pairs with it at
    26. Concretely, the dual sweep merges two cubes through their shared 2-cell, at
    *that 2-cell's value* -- not by plain cube adjacency. Every non-kept 2-cell has
    a masked corner ``m``, and both cubes adjacent to it lie in ``blocks(m)``, the 8
    cubes containing ``m``, which are mutually face-connected through 2-cells that
    all contain ``m``. So the tau-time dual components are generated by the
    ``blocks(m)``, joined exactly when ``blocks(m)`` and ``blocks(m')`` share a cube,
    i.e. when ``|m - m'|_inf <= 1``. Hence tau-time dual components ==
    26-connected components of masked voxels.

    The tempting alternative -- 6-connected components of non-kept *cubes* -- is
    strictly coarser and **destroys cavities silently**. Minimal counterexample:
    mask exactly two interior voxels ``(0,0,0)`` and ``(2,0,0)``. The cubes
    ``[0,1]^3`` and ``[1,2]x[0,1]x[0,1]`` are 6-adjacent and both non-kept, but the
    2-cell they share at ``x = 1`` has four kept corners, so it is a *kept* 2-cell
    and they do not merge before the background value. The filtration has two
    cavities; the 6-cube rule reports one.

The **same** labelling is also what the dim-1 cone apexes use, and that is sound:
the cone's correctness argument needs only that no non-kept cell is shared between
two apexes, which this labelling satisfies by construction -- a shared non-kept cell
would carry a masked corner, putting both cubes in the same pocket. So one labelling
serves both consumers.

It is **canonicalised**: ids are assigned in raster order of first occurrence, so
every backend (scipy / cc3d / cupy) produces a bit-identical int32 array. This is
load-bearing, not cosmetic -- the virtual cell indices in the C++ matcher derive
from pocket ids, so the virtual-slice tie-break order depends on them.
"""

from __future__ import annotations

import itertools
from dataclasses import dataclass

import numpy as np

__all__ = ["PocketLabels", "kept_cubes", "canonical_relabel", "label_pockets"]

try:
    import cc3d as _cc3d  # noqa: F401
    _HAVE_CC3D = True
except ImportError:  # pragma: no cover - environment-dependent
    _HAVE_CC3D = False


@dataclass(frozen=True)
class PocketLabels:
    """Pockets of one kept mask. All label arrays are int32 with 0 == "kept"."""

    fine: np.ndarray
    """Voxel grid, shape == keep.shape. 0 on kept voxels, 1..n_fine on masked ones."""
    n_fine: int
    cube_fine: np.ndarray
    """Cube grid, shape == keep.shape - 1. 0 on kept cubes, else the fine id of the
    cube's masked corners (all masked corners of one cube share a fine id, since they
    lie within L_inf <= 1 of each other)."""
    fine_touches_boundary: np.ndarray
    """bool, length n_fine + 1; entry 0 is False. True iff the fine pocket contains a
    masked voxel on a grid face -- equivalently, iff it reaches the dual UF's
    exterior sentinel at tau, so it must be pre-unioned with it and can never die."""

    @property
    def n_fine_interior(self) -> int:
        return int(self.n_fine - self.fine_touches_boundary.sum())


def kept_cubes(keep: np.ndarray) -> np.ndarray:
    """Top cells all of whose 2**ndim corners are kept. Shape is ``keep.shape - 1``.

    Written as an explicit AND over the 2**ndim corner shifts rather than a
    ``minimum_filter``, so there is no filter-origin convention to get wrong.
    """
    nd = keep.ndim
    if any(s < 2 for s in keep.shape):
        # Degenerate axis: no top cells at all. Slice rather than allocate, so the
        # result keeps the input's array type (numpy or cupy).
        return keep[tuple(slice(0, max(s - 1, 0)) for s in keep.shape)]
    out = None
    for off in itertools.product((0, 1), repeat=nd):
        sl = tuple(slice(o, keep.shape[i] - 1 + o) for i, o in enumerate(off))
        out = keep[sl].copy() if out is None else (out & keep[sl])
    return out


def _xp(a):
    """numpy or cupy, whichever owns `a`."""
    if type(a).__module__.split(".")[0] == "cupy":
        import cupy
        return cupy
    return np


def canonical_relabel(lab, n: int):
    """Renumber 1..n labels by raster order of first occurrence.

    Backends disagree on which component gets which id; this pins it, so
    scipy/cc3d/cupy become bit-identical and the C++ virtual-cell ordering is
    reproducible. Works on numpy or cupy arrays and stays on the input's device.
    Returns ``(relabelled_int32, n_actually_present)``.
    """
    xp = _xp(lab)
    lab = xp.ascontiguousarray(lab)
    if n == 0:
        return xp.zeros(lab.shape, dtype=xp.int32), 0
    flat = lab.reshape(-1)
    hi = int(flat.max())
    if hi == 0:
        return xp.zeros(lab.shape, dtype=xp.int32), 0

    # First occurrence per label, without sorting the whole array.
    if xp is np:
        # numpy guarantees last-write-wins for duplicate fancy indices, so
        # scattering in REVERSE raster order leaves each label's smallest index.
        # One O(N) scatter instead of np.unique's O(N log N) sort.
        first = np.full(hi + 1, -1, dtype=np.int64)
        first[flat[::-1]] = np.arange(flat.size - 1, -1, -1, dtype=np.int64)
        present = np.flatnonzero(first >= 0)
    else:
        # cupy's __setitem__ with duplicate indices is UNDEFINED, so the reverse
        # scatter above is not device-safe. cupyx.scatter_min is.
        import cupyx
        first = xp.full(hi + 1, flat.size, dtype=xp.int64)
        cupyx.scatter_min(first, flat, xp.arange(flat.size, dtype=xp.int64))
        present = xp.flatnonzero(first < flat.size)
    present = present[present != 0]
    order = present[xp.argsort(first[present], kind="stable")]
    lut = xp.zeros(hi + 1, dtype=xp.int32)
    lut[order] = xp.arange(1, order.size + 1, dtype=xp.int32)
    return lut[lab], int(order.size)


def _label_cpu(mask: np.ndarray, backend: str):
    """26-connected (8 in 2D) CCL of a boolean mask -> (int32 labels, count).

    **cc3d is opt-in and must not be the default: it is wrong in 2D.** On 2.3 %
    of random 2D masks (35/1500; 0/1500 in 3D) it assigns a nonzero label to a
    BACKGROUND voxel. Silently, and the label is a real component's, so nothing
    downstream would notice: it would just move a pocket boundary. It is kept as
    a selectable backend, but `auto` uses scipy, and ``label_pockets`` checks the
    label support on every call.
    """
    if not mask.any():
        return np.zeros(mask.shape, dtype=np.int32), 0
    if backend == "cc3d":
        import cc3d

        conn = {2: 8, 3: 26}[mask.ndim]
        lab = cc3d.connected_components(np.ascontiguousarray(mask), connectivity=conn)
        return lab.astype(np.int32, copy=False), int(lab.max())
    from scipy.ndimage import generate_binary_structure, label as ndi_label

    lab, n = ndi_label(mask, structure=generate_binary_structure(mask.ndim, mask.ndim))
    return lab.astype(np.int32, copy=False), int(n)


def _label_cupy(mask):
    """cupyx CCL on device. `mask` is a cupy bool array; returns (cupy int32, n)."""
    import cupy as cp
    from cupyx.scipy.ndimage import label as cp_label

    if not bool(mask.any()):
        return cp.zeros(mask.shape, dtype=cp.int32), 0
    st = cp.ones((3,) * mask.ndim, dtype=cp.int32)  # full connectivity: 26 / 8
    lab, n = cp_label(mask, structure=st)
    return lab.astype(cp.int32, copy=False), int(n)


def label_pockets(keep: np.ndarray, backend: str = "auto") -> PocketLabels:
    """Pocket labelling of a kept mask.

    ``keep``: boolean array, True on kept voxels. ``backend`` is one of
    ``"auto"`` (cupy if ``keep`` is a cupy array, else scipy), ``"scipy"``,
    ``"cc3d"``, ``"cupy"``. Every backend returns the same canonical int32 arrays
    on the host.
    """
    if backend not in ("auto", "scipy", "cc3d", "cupy"):
        raise ValueError(f"unknown backend {backend!r}")
    is_device = type(keep).__module__.split(".")[0] == "cupy"
    if backend == "auto":
        # scipy, NOT cc3d: cc3d is faster but is WRONG in 2D -- see the
        # _label_cpu docstring. The fast path is the cupy backend.
        backend = "cupy" if is_device else "scipy"
    if backend == "cupy" and not is_device:
        import cupy as cp

        keep = cp.asarray(keep)
        is_device = True
    if backend != "cupy" and is_device:
        keep = keep.get()
        is_device = False

    if keep.ndim not in (2, 3):
        raise ValueError("2D or 3D masks only")

    if is_device:
        import cupy as cp
        xp = cp
        keep_a = keep.astype(cp.bool_, copy=False)
        label_fn = _label_cupy
    else:
        xp = np
        keep_a = np.ascontiguousarray(keep.astype(bool, copy=False))
        label_fn = lambda m: _label_cpu(m, backend)  # noqa: E731

    # Everything below is array-module generic and stays on the input's device;
    # only the finished int32 tables cross the PCIe bus.
    fine_raw, n_fine = label_fn(~keep_a)
    kc = kept_cubes(keep_a)
    fine, n_fine = canonical_relabel(fine_raw, n_fine)

    # cube -> fine id. Every non-kept cube has at least one masked corner, and all
    # of its masked corners lie within L_inf <= 1 of each other, hence in one fine
    # pocket, so a max over the 2**ndim corner labels is exact (kept corners are 0).
    nd = keep_a.ndim
    cube_fine = xp.zeros(kc.shape, dtype=xp.int32)
    if cube_fine.size:
        for off in itertools.product((0, 1), repeat=nd):
            sl = tuple(slice(o, keep_a.shape[i] - 1 + o) for i, o in enumerate(off))
            xp.maximum(cube_fine, fine[sl], out=cube_fine)
        cube_fine[kc] = 0

    touches = xp.zeros(n_fine + 1, dtype=xp.bool_)
    for axis in range(nd):
        for idx in (0, -1):
            face = xp.take(fine, idx, axis=axis)
            ids = xp.unique(face)
            touches[ids[ids != 0]] = True
    touches[0] = False

    # Support invariant, checked on every call: the labelling must be nonzero
    # exactly on the masked voxels. It is one O(N) boolean compare against two
    # CCLs, and it is what turns a backend defect (cc3d in 2D, and whatever
    # comes next) into a loud failure instead of silently-shifted pocket ids,
    # which nothing downstream could detect.
    if ((fine != 0) != (~keep_a)).any():
        raise RuntimeError(
            f"pocket labelling backend {backend!r} produced labels whose "
            "support is not exactly the masked voxels -- see the _label_cpu "
            "docstring for the known cc3d 2D defect")

    if is_device:
        fine, cube_fine, touches = (cp.asnumpy(fine), cp.asnumpy(cube_fine),
                                    cp.asnumpy(touches))

    return PocketLabels(fine=np.ascontiguousarray(fine), n_fine=n_fine,
                        cube_fine=np.ascontiguousarray(cube_fine),
                        fine_touches_boundary=touches)
